FROM node:20

WORKDIR /app

RUN npm i --global pnpm

COPY ./package.json ./package.json
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml

RUN pnpm i --ignore-scripts --frozen-lockfile

COPY ./ ./

RUN pnpm run db:prisma

CMD pnpm run start:docker
