FROM node:20

WORKDIR /app

COPY ./package.json ./package.json
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml

RUN pnpm i --ignore-scripts

ADD ./prisma ./prisma

RUN pnpm run prepare

ADD ./ ./

CMD pnpm run start:docker
