FROM node:20

WORKDIR /app

COPY ./package.json ./package.json
COPY ./yarn.lock ./yarn.lock

RUN yarn install --ignore-scripts

ADD ./prisma ./prisma

RUN yarn prepare

ADD ./ ./

CMD yarn start:docker
