export enum TimezoneEnum {
	AmericaAraguaina = 'AmericaAraguaina',
	AmericaBahia = 'AmericaBahia',
	AmericaBelem = 'AmericaBelem',
	AmericaBoa_Vista = 'AmericaBoa_Vista',
	AmericaCampo_Grande = 'AmericaCampo_Grande',
	AmericaCuiaba = 'AmericaCuiaba',
	AmericaEirunepe = 'AmericaEirunepe',
	AmericaFortaleza = 'AmericaFortaleza',
	AmericaMaceio = 'AmericaMaceio',
	AmericaManaus = 'AmericaManaus',
	AmericaNoronha = 'AmericaNoronha',
	AmericaPorto_Velho = 'AmericaPorto_Velho',
	AmericaRecife = 'AmericaRecife',
	AmericaRio_Branco = 'AmericaRio_Branco',
	AmericaSantarem = 'AmericaSantarem',
	AmericaSao_Paulo = 'AmericaSao_Paulo',
}
