export enum TimezoneEnum {
	'America/Araguaina' = 'America/Araguaina',
	'America/Bahia' = 'America/Bahia',
	'America/Belem' = 'America/Belem',
	'America/Boa_Vista' = 'America/Boa_Vista',
	'America/Campo_Grande' = 'America/Campo_Grande',
	'America/Cuiaba' = 'America/Cuiaba',
	'America/Eirunepe' = 'America/Eirunepe',
	'America/Fortaleza' = 'America/Fortaleza',
	'America/Maceio' = 'America/Maceio',
	'America/Manaus' = 'America/Manaus',
	'America/Noronha' = 'America/Noronha',
	'America/Porto_Velho' = 'America/Porto_Velho',
	'America/Recife' = 'America/Recife',
	'America/Rio_Branco' = 'America/Rio_Branco',
	'America/Santarem' = 'America/Santarem',
	'America/Sao_Paulo' = 'America/Sao_Paulo',
}
