name: dbdocs-validate

on:
  pull_request:
    branches:
      - master
    paths:
      - '**/*.prisma'

jobs:
  dbdocs-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install prisma && dbdocs
        run: yarn add -D dbdocs prisma prisma-dbml-generator

      - name: Generate schema.dbml
        run: npx prisma generate --generator dbml

      - name: Validate dbdocs
        run: npx dbdocs validate ./prisma/schema.dbml
