name: dbdocs-validate

on:
  pull_request:
    branches:
      - master
    paths:
      - '**/*.prisma'

jobs:
  dbdocs-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install prisma & dbdocs
        run: yarn add --ignore-scripts -D dbdocs prisma prisma-dbml-generator

      - name: Generate schema.dbml
        run: npx prisma generate --generator dbml

      - name: Validate dbdocs
        run: npx dbdocs validate ./prisma/schema.dbml
