name: openapi-deploy

on:
  pull_request:
    branches:
      - master
    paths:
      - "openapi/*"

jobs:
  openapi-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - uses: pnpm/action-setup@v3

      - name: Validate openapi
        run: pnpm run lint:openapi

      - name: GitHub Action
        uses: readmeio/rdme@v8
        with:
          rdme: docs ./openapi/bundle.yaml --key=${{ secrets.README_API_KEY }} --version=1.0
