name: openapi-validate

on:
  pull_request:
    branches:
      - master
    paths:
      - 'openapi/*'

jobs:
  openapi-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install redocly
        run: yarn add -D @redocly/cli

      - name: Validate openapi
        run: yarn openapi:lint
