name: prisma-validate

on:
  pull_request:
    branches:
      - master
    paths:
      - '**/*.prisma'

jobs:
  prisma-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install prisma
        run: yarn add --ignore-scripts -D prisma

      - name: Validate prisma
        env:
          DATABASE_URL: postgresql://user:password@host:port/database?schema=public
        run: npx prisma validate
