name: tests-validate

on:
  pull_request:
    branches:
      - master
    paths:
      - 'src/*'
      - 'tests/*'

jobs:
  tests-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: yarn install --ignore-scripts

      - name: Gen prisma types
        run: yarn db:prisma

      - name: Run tests
        run: yarn test:cov
