name: tests-validate

on:
  pull_request:
    branches:
      - master
    paths:
      - "src/*"
      - "tests/*"

jobs:
  tests-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install --ignore-scripts

      - name: Gen prisma types
        run: pnpm run db:prisma

      - name: Run tests
        run: pnpm run test:cov
